

// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.com/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Do not make changes directly to this file - edit the template instead.
//
// The following connection settings were used to generate this file:
//     Configuration file:     "Web\Web.config"
//     Connection String Name: "DefaultConnection"
//     Connection String:      "Data Source=klb0jreghr.database.windows.net,1433;Initial Catalog=AzureRealms;Integrated Security=False;User Id=HighTechHangoutDB@klb0jreghr;password=**zapped**;;Persist Security Info=False;Pooling=False;MultipleActiveResultSets=False;Connect Timeout=60;Encrypt=False;TrustServerCertificate=True"
// ------------------------------------------------------------------------------------------------
// Database Edition       : SQL Azure
// Database Engine Edition: Azure

#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace Data.Entities
{

}

